language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm
 
matrix:
    allow_failures:
        - php: hhvm

before_script:
  - curl -s http://getcomposer.org/installer | php -- --quiet
  - php composer.phar install --dev

script:
  - php bin/phpunit --coverage-text
