language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: '7.4'

install:
  - composer update --prefer-dist --no-progress --no-suggest --ansi

script:
  - vendor/bin/simple-phpunit --coverage-text
